name: Deploy to Firebase
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 5: Deploy to Firebase
      - name: Deploy to Firebase
        env:
          FIREBASE_API_KEY: ${{ secrets.API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.APP_ID }}
