name: Deploy to Firebase
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 5: Deploy to Firebase
      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
